// Generated by CoffeeScript 1.12.4
var AnimatedValue, ValueMapper, createValueMapper, frozen, isDev, methods;

AnimatedValue = require("Animated").AnimatedValue;

frozen = require("Property").frozen;

ValueMapper = require("ValueMapper");

isDev = require("isDev");

module.exports = function(type) {
  return type.defineMethods(methods);
};

methods = {
  defineAnimatedValues: function(values) {
    var mapValues;
    mapValues = createValueMapper(values, false);
    this._delegate._phases.init.push(function(args) {
      return mapValues(this, args);
    });
  },
  defineNativeValues: function(values) {
    var mapValues;
    mapValues = createValueMapper(values, true);
    this._delegate._phases.init.push(function(args) {
      return mapValues(this, args);
    });
  }
};

createValueMapper = function(values, isNative) {
  return ValueMapper(values, function(obj, key, value) {
    if (value !== void 0) {
      value = AnimatedValue(value, {
        isNative: isNative
      });
      if (isDev) {
        frozen.define(obj, key, {
          value: value
        });
      } else {
        obj[key] = value;
      }
    }
  });
};
