// Generated by CoffeeScript 1.12.4
var Event, Mixin, defineListeners, frozen, rootMixin;

frozen = require("Property").frozen;

Event = require("eve");

Mixin = require("./Mixin");

module.exports = function(type) {
  return type.defineMethods({
    defineListeners: defineListeners
  });
};

defineListeners = function(createListeners) {
  var delegate;
  delegate = this._delegate;
  if (delegate._needs("listeners")) {
    delegate.addMixin(rootMixin);
  }
  delegate.willMount(function() {
    var listeners, onAttach;
    listeners = this.__listeners;
    onAttach = Event.didAttach(function(listener) {
      return listeners.push(listener);
    });
    createListeners.call(this);
    return onAttach.detach();
  });
};

rootMixin = (function() {
  var mixin;
  mixin = Mixin();
  mixin.defineValues(function() {
    return {
      __listeners: []
    };
  });
  mixin.willUnmount(function() {
    var i, len, listener, ref;
    ref = this.__listeners;
    for (i = 0, len = ref.length; i < len; i++) {
      listener = ref[i];
      listener.detach();
    }
    this.__listeners = [];
  });
  return mixin.apply;
})();
