// Generated by CoffeeScript 1.12.4
var AnimatedProps, Component, ListenerMixin, React, Type, mixin, requireNativeComponent, sync, type;

AnimatedProps = require("Animated").AnimatedProps;

ListenerMixin = require("Event").ListenerMixin;

requireNativeComponent = require("requireNativeComponent");

React = require("react");

Type = require("Type");

sync = require("sync");

Component = require("./Component");

type = Type("NativeComponent");

type.inherits(Component);

type.defineArgs([String]);

type.initInstance(function() {
  return mixin.apply(this);
});

type.overrideMethods({
  build: function() {
    var name, ref, render;
    name = this._name;
    render = (ref = this._render) != null ? ref : (function() {
      var componentType;
      componentType = requireNativeComponent(name);
      return function(props) {
        return React.createElement(componentType, props);
      };
    })();
    this._render = function() {
      var props;
      props = this._isMounting ? this._animatedProps.__getAllValues() : this._animatedProps.__getNonNativeValues();
      props.ref = this._setChild;
      return render.call(this, props);
    };
    return this.__super(arguments);
  }
});

module.exports = type.build();

mixin = Component.Mixin();

mixin.defineValues({
  _isMounting: false,
  _child: null,
  _queuedProps: null,
  _animatedProps: function() {
    return AnimatedProps(this.constructor.propTypes);
  }
});

mixin.willMount(function() {
  this._isMounting = true;
  return this._animatedProps.attach(this.props);
});

mixin.didMount(function() {
  return this._isMounting = false;
});

mixin.defineListeners(function() {
  return this._animatedProps.didSet(this.setNativeProps);
});

mixin.willReceiveProps(function(nextProps) {
  return this._animatedProps.attach(nextProps);
});

mixin.willUnmount(function() {
  return this._animatedProps.detach();
});

mixin.defineBoundMethods({
  setNativeProps: function(newProps) {
    if (this._child === null) {
      this._queuedProps = newProps;
    } else {
      this._child.setNativeProps(newProps);
    }
  },
  _setChild: function(view) {
    if (view && this._queuedProps) {
      view.setNativeProps(this._queuedProps);
      this._queuedProps = null;
    }
    this._child = view;
    this._animatedProps.setAnimatedView(view);
  }
});
