// Generated by CoffeeScript 1.12.4
var ElementType, NamedFunction, ReactCurrentOwner, ReactElement, applyMixins, assertType, createType, isType, setKind, setType;

ReactCurrentOwner = require("ReactCurrentOwner");

NamedFunction = require("NamedFunction");

ReactElement = require("ReactElement");

assertType = require("assertType");

setType = require("setType");

setKind = require("setKind");

isType = require("isType");

ElementType = NamedFunction("ElementType", function(componentType) {
  var elementType;
  assertType(componentType, Function.Kind);
  elementType = createType(componentType);
  elementType.componentType = componentType;
  return setType(elementType, ElementType);
});

module.exports = setKind(ElementType, Function);

applyMixins = function(mixins, props) {
  var i, key, len, mixin, value;
  for (i = 0, len = mixins.length; i < len; i++) {
    mixin = mixins[i];
    if (mixin == null) {
      continue;
    }
    for (key in mixin) {
      value = mixin[key];
      if (props[key] === void 0) {
        props[key] = value;
      }
    }
  }
};

createType = function(componentType) {
  var createElement, initProps;
  initProps = componentType.initProps;
  return createElement = function(props, delegate) {
    var key, mixins, ref;
    assertType(props, Object.Maybe, "props");
    if (props != null) {
      if (Object.isFrozen(props)) {
        throw Error("'props' cannot be frozen!");
      }
      key = props.key;
      if (key != null) {
        delete props.key;
        key = String(key);
      }
      ref = props.ref;
      if (ref != null) {
        delete props.ref;
        assertType(ref, Function, "props.ref");
      }
      mixins = props.mixins;
      if (mixins != null) {
        delete props.mixins;
        assertType(mixins, Array, "props.mixins");
        applyMixins(mixins, props);
      }
    } else {
      props = {};
    }
    if (initProps) {
      props = initProps(props);
    }
    props.delegate = delegate || null;
    return ReactElement.apply(null, [componentType, key, ref, null, null, ReactCurrentOwner.current, props]);
  };
};
